version: '3.1'

services:
  

  userserver:
    build: ./userserver
    ports:
      - 50053:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "database" 
    depends_on: 
      - database


  database:
    image: postgres
    ports:
      - 5432:5432