version: '3.1'

services:
  shippyclient:
    build: ./shippyclient
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on: 
      - shippyserver

  shippyserver:
    build: ./shippyserver
    ports:
      - "50051:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on: 
      - datastore

  shippyvessel:
      build: ./shippyvessel
      ports:
        - "50052:50051"
      environment:
        MICRO_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"
        DB_HOST: "datastore:27017"
      depends_on: 
        - datastore

  datastore:
    image: mongo
    ports:
      - 27017:27017